### ISSUE TITLE
Routing broken following Ubuntu 21.10 Upgrade

### ISSUE THREAD

**Issue by mf-lit** [canonical/microk8s#2709]
I was previously running v1.19 under Ubuntu 21.04 without issue, but following upgrade to 21.10 the cluster was pretty much hosed. Since then I've both `microk8s reset` and `snap remove microk8s` and installed the current edge release (v1.22.3).

The cluster starts but the calico controller gets into a Crash Loop with errors like:

```
2021-11-04 12:32:04.139 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W1104 12:32:04.140304       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021-11-04 12:32:04.140 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2021-11-04 12:32:07.208 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=Get "https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.152.183.1:443: connect: no route to host
2021-11-04 12:32:07.208 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get "https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.152.183.1:443: connect: no route to host
```

If I try running any extensions (which I realise is a bit pointless while calico is broken) I see similar "no route to host" errors from pods trying to contact the Kube API.

I'm pretty much lost at this point. I suspect this may have something to do with cgroups2 but I'm speculating.
Any advice on troubleshooting this would be much appreciated.

[inspection-report-20211104_123715.tar.gz](https://github.com/ubuntu/microk8s/files/7474805/inspection-report-20211104_123715.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @mf-lit, maybe calico is not selecting the right network interface. Let's try this, go to `/var/snap/microk8s/current/args/cni-network/cni.yaml`, find the section that says:
```
            - name: IP_AUTODETECTION_METHOD
              value: "first-found"
```
Set the value of `IP_AUTODETECTION_METHOD` from `first-found` to `can-reach=www.google.com`.

Apply the new manifest with `microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml`.

You can read more on the auto detect options at https://docs.projectcalico.org/networking/ip-autodetection

**Comment by arnobl** [comment]
I also had this problem after an upgrade of my system to Fedora 35 (October 2021).
I fixed the issue but I do not really know the exact commands that fixed my problem.
This is what I did (to investigate with caution):
`sudo snap remove microk8s --purge`
I removed the `.kube` folder in my homedir.
`firewall-cmd --list-all | grep masquerade` gave my `masquerade: no` so that (https://stackoverflow.com/questions/68213989/kubedns-no-route-to-host-for-kubernetes-default):
`firewall-cmd --add-masquerade --permanent` 
I restarted my computer.

`sudo snap install microk8s --classic` (it installed 1.22.2 stable)
`microk8s.enable dns` (or all the add-ons you want)

all pods from `microk8s.kubectl get all --all-namespaces` are now ok (coredns, calico, etc.)

**Comment by arnobl** [comment]
In fact the workaround I did to remove this issue is `microk8s disable ha-cluster --force`

By reactivating ha-cluster I still have this issue...

**Comment by remartens** [comment]
I had the same issue after upgradring my Raspberry PI to Ubuntu 21.10. When I looked at the [installation steps](https://microk8s.io/docs/install-alternatives#heading--arm) again to reinstall MicroK8S, I noticed the following note:

> On Ubuntu 21.10: Install extra kernel modules with `sudo apt install linux-modules-extra-raspi` and restart MicroK8s with `sudo microk8s stop; sudo microk8s start`.

Installing the extra Linux kernel modules fixed it for me.

**Comment by mf-lit** [comment]
> Hi @mf-lit, maybe calico is not selecting the right network interface. Let's try this, go to `/var/snap/microk8s/current/args/cni-network/cni.yaml`, find the section that says:

@ktsakalozos Apologies for taking so long to come back on this. Unfortunately this change made no difference, routing errors remain the same.

> In fact the workaround I did to remove this issue is microk8s disable ha-cluster --force

I tried this too. Looks like it swaps calico for flannel, but nevertheless no improvement - I now get similar errors from the `hostpath-provisioner` pod unable to reach the API.
